services:
  traefik:
    image: traefik:v3.7
    restart: unless-stopped

    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"

    ports:
      - "80:80"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  paperless:
    environment:
      PAPERLESS_URL: http://${APP_HOST}

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperless.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.paperless.entrypoints=web"
      - "traefik.http.services.paperless.loadbalancer.server.port=8000"