api:
  dashboard: true
  insecure: true

providers:
  docker:
    exposedByDefault: false
    network: paperless_network

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${TRAEFIK_ACME_EMAIL}
      storage: /data/acme.json
      tlsChallenge: {}