services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - ${PWD}/redisdata:/data
    networks:
      - paperless_network

  db:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - ${PWD}/data/postgres:/var/lib/postgresql/data
      # - ${PWD}/config/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    environment:
      POSTGRES_DB: ${PAPERLESS_DBNAME}
      POSTGRES_USER: ${PAPERLESS_DBUSER}
      POSTGRES_PASSWORD: ${PAPERLESS_DBPASSWORD}
    networks:
      - paperless_network

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    volumes:
      - ${PWD}/data:/usr/src/paperless/data
      - ${PWD}/media:/usr/src/paperless/media
      - ${PWD}/export:/usr/src/paperless/export
      - ${PWD}/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: ${PAPERLESS_REDIS}
      PAPERLESS_DBHOST: ${PAPERLESS_DBHOST}
      PAPERLESS_DBNAME: ${PAPERLESS_DBNAME}
      PAPERLESS_DBUSER: ${PAPERLESS_DBUSER}
      PAPERLESS_DBPASSWORD: ${PAPERLESS_DBPASSWORD}
      PAPERLESS_TIKA_ENABLED: ${PAPERLESS_TIKA_ENABLED}
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: ${PAPERLESS_TIKA_GOTENBERG_ENDPOINT}
      PAPERLESS_TIKA_ENDPOINT: ${PAPERLESS_TIKA_ENDPOINT}
      PAPERLESS_URL: ${PAPERLESS_URL}
      PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY}
      PAPERLESS_TIME_ZONE: ${PAPERLESS_TIME_ZONE}
      PAPERLESS_OCR_LANGUAGE: ${PAPERLESS_OCR_LANGUAGE}
      PAPERLESS_OCR_LANGUAGES: ${PAPERLESS_OCR_LANGUAGES}
      PAPERLESS_ADMIN_USER: ${PAPERLESS_ADMIN_USER}
      PAPERLESS_ADMIN_PASSWORD: ${PAPERLESS_ADMIN_PASSWORD}
    env_file:
      - .env
    networks:
      - paperless_network

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    networks:
      - paperless_network

  tika:
    image: docker.io/apache/tika:latest
    restart: unless-stopped
    networks:
      - paperless_network

networks:
  paperless_network:
    external: true